name: Test

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
          cache: true
      - name: static analysis checker
        uses: k8s-school/golang-github-actions@v1.1.3
      - name: go-mnd
        uses: tommy-muehle/go-mnd@v2.2.0
      - name: Install dependencies
        run: |
          go get ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        env:
          ENV: TEST
        run: go test -v ./...
