name: Go package

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
          cache: true
      - name: Install dependencies
        run: |
          go get ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        env:
          ENV: TEST
        run: go test -v ./...
